// <auto-generated />
namespace HouseRentManagementApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class January012017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(January012017));
        
        string IMigrationMetadata.Id
        {
            get { return "201701121004579_January01,2017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
